"""Transient-profile reconstruction using clean synthetic dots."""

PRESET_NAME = "Stylized Transient Hydrogen Dot Field"

RENDER_MODE = "area_summary_dots"
FIGURE_SIZE = (13, 6)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = False
TITLE = "Hydrogen Distribution (Stylized)"
X_LABEL = "Width"
Y_LABEL = "Height"

COLOR_EMPTY = "#F2F2F2"
COLOR_AVAILABLE_SPOT = "#2166AC"
COLOR_HYDROGEN = "#B2182B"
COLOR_CONCENTRATION_LINE = "#253494"
DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 1.0
DOT_ALPHA_HYDROGEN = 1.0

SHOW_MAIN_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = False
SHOW_NET_FLUX_PANEL = False

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 5
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = False
PROFILE_HALF_TRANSITION_COLOR = "#707070"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = False
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Spot Region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = False
SHOW_LEFT_RIGHT_ANNOTATIONS = False
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = False
SHOW_TRAP_LAYER_ANNOTATION = False
ANNOTATION_FONT_SIZE = 10
ANNOTATION_COLOR = "#202020"

CUSTOM_RECT_REGIONS = []

AREA_SUMMARY_TOTAL_DOTS = 5000
AREA_SUMMARY_DENSITY_MODE = "available_sites"
AREA_SUMMARY_MIN_DOTS_PER_AREA = 30
AREA_SUMMARY_RANDOM_SEED = 104724
# The transient preset preserves the measured concentration gradient by column.
AREA_SUMMARY_CONCENTRATION_MODE = "saved_x_profile"
AREA_SUMMARY_LINEAR_CONCENTRATION = (100, 0)
AREA_SUMMARY_X_PROFILE_SIGMA = 20.0
# Exact rounded red-dot counts are assigned within slices this many matrix columns wide.
AREA_SUMMARY_CONCENTRATION_BIN_WIDTH = 40
AREA_SUMMARY_POSITION_MODE = "even_hex"
AREA_SUMMARY_MIN_DOT_SPACING = 9.0
# Render both styles by default. Set this to one item, for example ("organic",),
# or set it to None to render only AREA_SUMMARY_SHAKE_MODE without a filename suffix.
AREA_SUMMARY_SHAKE_OUTPUT_MODES = ("organic", "clustered")
AREA_SUMMARY_SHAKE_MODE = "organic"
AREA_SUMMARY_SHAKE_STRENGTH = None
AREA_SUMMARY_SHAKE_PASSES = None
AREA_SUMMARY_SHAKE_ATTEMPTS = 8
AREA_SUMMARY_CLUSTER_COUNT = 16
AREA_SUMMARY_CLUSTER_ATTRACTION = 0.75
# "combined_a_b" shakes all A+B dots together inside one union geometry.
# "per_area" gives Area A, Area B, the spot, and the trap independent fields.
AREA_SUMMARY_CLUSTER_SCOPE = "combined_a_b"
AREA_SUMMARY_POSITION_JITTER = 0.42
AREA_SUMMARY_POSITION_INSET = 5
AREA_SUMMARY_DOT_SIZE = 18
AREA_SUMMARY_DOT_ALPHA = 0.96
AREA_SUMMARY_DOT_EDGE_COLOR = "#FFFFFF"
AREA_SUMMARY_DOT_EDGE_WIDTH = 0.25
AREA_SUMMARY_BACKGROUND_COLOR = "#FAFAFA"
# A/B averages hide the transient gradient and are intentionally omitted here.
AREA_SUMMARY_SHOW_AREA_LABELS = False
AREA_SUMMARY_SHOW_EXPLANATION = False

AREA_SUMMARY_SHOW_SOURCE_SINK_BANDS = True
AREA_SUMMARY_SHOW_SOURCE_SINK_LABELS = False
# Make the red source and blue sink bands three times their saved physical width.
AREA_SUMMARY_SOURCE_SINK_BAND_WIDTH_SCALE = 3.0
AREA_SUMMARY_SOURCE_SINK_EDGE_COLOR = "#303030"
AREA_SUMMARY_SOURCE_SINK_EDGE_WIDTH = 0.8
AREA_SUMMARY_SHOW_HALF_DIVIDER = False
AREA_SUMMARY_HALF_DIVIDER_COLOR = "#A0A0A0"

SHOW_SPECIAL_REGION_OUTLINES = True
SPECIAL_REGION_OUTLINE_COLOR = "#202020"
SPECIAL_REGION_OUTLINE_WIDTH = 1.4
SPECIAL_REGION_OUTLINE_STYLE = "--"
# Shade the spot behind its dots; the trap keeps the shared dashed outline above.
SHOW_SPOT_REGION_FILL = True
SPOT_REGION_FILL_COLOR = "#D9D9D9"
SPOT_REGION_FILL_ALPHA = 1.0
SPOT_REGION_OUTLINE_COLOR = "#202020"
SPOT_REGION_OUTLINE_WIDTH = 0.8
SPOT_REGION_OUTLINE_STYLE = "-"

ANNOTATION_STROKE_COLOR = "#FFFFFF"
ANNOTATION_STROKE_WIDTH = 3.5
ANNOTATION_BOX_ENABLED = True
ANNOTATION_BOX_FACE_COLOR = "#FFFFFF"
ANNOTATION_BOX_EDGE_COLOR = "#707070"
ANNOTATION_BOX_ALPHA = 0.90

SHOW_FRAME_SUPTITLE = False
