"""Matrix-shaped reconstruction using area averages and clean synthetic dots."""

PRESET_NAME = "Stylized Area-Average Dot Field"

RENDER_MODE = "area_summary_dots"
FIGURE_SIZE = (13, 6)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = False
TITLE = "Area-Averaged Hydrogen Distribution (Stylized)"
X_LABEL = "Width"
Y_LABEL = "Height"

COLOR_EMPTY = "#F2F2F2"
COLOR_AVAILABLE_SPOT = "#2166AC"
COLOR_HYDROGEN = "#B2182B"
COLOR_CONCENTRATION_LINE = "#253494"
DIFFUSION_SPEED_COLORS = [
    "#B2182B",
    "#EF8A62",
    "#2166AC",
    "#762A83",
    "#1B7837",
    "#008B8B",
    "#202020",
]

DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 1.0
DOT_ALPHA_HYDROGEN = 1.0

SHOW_MAIN_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = False
SHOW_DIFFUSION_SPEED_PANEL = False

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 5
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = False
PROFILE_HALF_TRANSITION_COLOR = "#707070"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = False
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Spot Region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = False
SHOW_LEFT_RIGHT_ANNOTATIONS = False
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = False
SHOW_TRAP_LAYER_ANNOTATION = False
ANNOTATION_FONT_SIZE = 10
ANNOTATION_COLOR = "#202020"

CUSTOM_RECT_REGIONS = []

AREA_SUMMARY_TOTAL_DOTS = 5000
AREA_SUMMARY_DENSITY_MODE = "available_sites"
AREA_SUMMARY_MIN_DOTS_PER_AREA = 30
AREA_SUMMARY_RANDOM_SEED = 104729
AREA_SUMMARY_POSITION_MODE = "even_hex"
AREA_SUMMARY_MIN_DOT_SPACING = 8.0
AREA_SUMMARY_SHAKE_MODE = "organic"
AREA_SUMMARY_SHAKE_STRENGTH = None
AREA_SUMMARY_SHAKE_PASSES = None
AREA_SUMMARY_SHAKE_ATTEMPTS = 8
AREA_SUMMARY_CLUSTER_COUNT = 8
AREA_SUMMARY_CLUSTER_ATTRACTION = 0.70
AREA_SUMMARY_POSITION_JITTER = 0.42
AREA_SUMMARY_POSITION_INSET = 5
AREA_SUMMARY_DOT_SIZE = 18
AREA_SUMMARY_DOT_ALPHA = 0.96
AREA_SUMMARY_DOT_EDGE_COLOR = "#FFFFFF"
AREA_SUMMARY_DOT_EDGE_WIDTH = 0.25
AREA_SUMMARY_BACKGROUND_COLOR = "#FAFAFA"
AREA_SUMMARY_SHOW_AREA_LABELS = True
AREA_SUMMARY_SHOW_EXPLANATION = False

AREA_SUMMARY_SHOW_SOURCE_SINK_BANDS = True
AREA_SUMMARY_SHOW_SOURCE_SINK_LABELS = False
AREA_SUMMARY_SOURCE_SINK_EDGE_COLOR = "#303030"
AREA_SUMMARY_SOURCE_SINK_EDGE_WIDTH = 0.8
AREA_SUMMARY_SHOW_HALF_DIVIDER = False
AREA_SUMMARY_HALF_DIVIDER_COLOR = "#A0A0A0"

SHOW_SPECIAL_REGION_OUTLINES = True
SPECIAL_REGION_OUTLINE_COLOR = "#202020"
SPECIAL_REGION_OUTLINE_WIDTH = 1.4
SPECIAL_REGION_OUTLINE_STYLE = "--"

ANNOTATION_STROKE_COLOR = "#FFFFFF"
ANNOTATION_STROKE_WIDTH = 3.5
ANNOTATION_BOX_ENABLED = True
ANNOTATION_BOX_FACE_COLOR = "#FFFFFF"
ANNOTATION_BOX_EDGE_COLOR = "#707070"
ANNOTATION_BOX_ALPHA = 0.90

SHOW_FRAME_SUPTITLE = False
