"""Standalone heatmap matching simple_1_region_source_with_heatmap."""

PRESET_NAME = "Initial-Setup Difference Heatmap"

RENDER_MODE = "pixels"
FIGURE_SIZE = (7.5, 6)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = True
TITLE = ""
X_LABEL = "Length"
Y_LABEL = "Height"
PANEL_TITLE_FONT_SIZE = 18
AXIS_LABEL_FONT_SIZE = 18
TICK_LABEL_FONT_SIZE = 16

COLOR_EMPTY = "#440154"
COLOR_AVAILABLE_SPOT = "#0000FF"
COLOR_HYDROGEN = "#FF0000"
COLOR_CONCENTRATION_LINE = "#253494"
DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 0.8
DOT_ALPHA_HYDROGEN = 0.95

SHOW_MAIN_PANEL = False
SHOW_HEATMAP_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = False
SHOW_NET_FLUX_PANEL = False
SHOW_FRAME_SUPTITLE = False

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 5
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = False
PROFILE_HALF_TRANSITION_COLOR = "#808080"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = True
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Spot Region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = False
SHOW_LEFT_RIGHT_ANNOTATIONS = False
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = False
SHOW_TRAP_LAYER_ANNOTATION = False
ANNOTATION_FONT_SIZE = 11
ANNOTATION_COLOR = "#FFFFFF"

CUSTOM_RECT_REGIONS = []

HEATMAP_MODE = "change_from_initial_setup"
HEATMAP_BASELINE_SNAPSHOT_INDEX = 0
HEATMAP_SIGMA = 28.0
HEATMAP_COLORMAP = "RdBu_r"
HEATMAP_DEVIATION_RANGE = (-10.0, 10.0)
HEATMAP_REFERENCE_MODE = "regional_bulk"
HEATMAP_RESPECT_AREA_BOUNDARIES = True
HEATMAP_SEPARATE_BASE_AREAS = False
HEATMAP_SHOW_CONTOURS = True
HEATMAP_CONTOUR_LEVELS = (-30, -20, -10, 10, 20, 30)
HEATMAP_CONTOUR_COLOR = "#303030"
HEATMAP_CONTOUR_ALPHA = 0.30
HEATMAP_SHOW_COLORBAR = True
HEATMAP_COLORBAR_ORIENTATION = "horizontal"
HEATMAP_COLORBAR_LABEL = "ΔH [%]"
HEATMAP_HORIZONTAL_COLORBAR_TICK_COUNT = 7

SHOW_SPECIAL_REGION_OUTLINES = True
SPECIAL_REGION_OUTLINE_COLOR = "#202020"
SPECIAL_REGION_OUTLINE_WIDTH = 1.4
SPECIAL_REGION_OUTLINE_STYLE = "--"
