"""A4-landscape single-region matrix with appendix annotations."""

PRESET_NAME = "Full-Sized 1 Region"

RENDER_MODE = "pixels"
FIGURE_SIZE = (11.69, 8.27)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = True
TITLE = ""
X_LABEL = "Length"
Y_LABEL = "Height"
PANEL_TITLE_FONT_SIZE = 18
AXIS_LABEL_FONT_SIZE = 18
TICK_LABEL_FONT_SIZE = 16
SHOW_SITE_STATE_LEGEND = True
SHOW_LEGEND = False
SITE_STATE_AVAILABLE_LABEL = "Available Lattice Sites"
SITE_STATE_OCCUPIED_LABEL = "Occupied Sites"
SITE_STATE_UNAVAILABLE_LABEL = "Unavailable Locations"
SITE_STATE_LEGEND_LOCATION = "upper right"
SITE_STATE_LEGEND_ANCHOR = (0.98, 0.98)
SITE_STATE_LEGEND_FONT_SIZE = 14.4
SITE_STATE_LEGEND_MARKER_AREA = 82

COLOR_EMPTY = "#440154"
COLOR_AVAILABLE_SPOT = "#0000FF"
COLOR_HYDROGEN = "#FF0000"
COLOR_CONCENTRATION_LINE = "#253494"
DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 0.8
DOT_ALPHA_HYDROGEN = 0.95

SHOW_MAIN_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = False
SHOW_NET_FLUX_PANEL = False
SHOW_FRAME_SUPTITLE = False

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 5
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = False
PROFILE_HALF_TRANSITION_COLOR = "#808080"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = True
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Spot Region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = True
SHOW_LEFT_RIGHT_ANNOTATIONS = False
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = True
SHOW_TRAP_LAYER_ANNOTATION = False
SHOW_BULK_ANNOTATION = True
BULK_ANNOTATION_LABEL = "Bulk Average"
BULK_ANNOTATION_POSITION = (0.22, 0.88)
SPOT_ANNOTATION_LABEL = "Spot Average"
SPOT_ANNOTATION_VERTICAL_OFFSET_SCALE = 1.35
SHOW_BULK_SOLUBILITY_IN_ANNOTATION = True
SHOW_SPOT_SOLUBILITY_IN_ANNOTATION = True
ANNOTATION_FONT_SIZE = 16
ANNOTATION_COLOR = "#FFFFFF"

CUSTOM_TEXT_ANNOTATIONS = (
    {
        "text": (
            "Transition acceptance probabilities:\n"
            r"$P_{\mathrm{acc}}(\mathrm{bulk}\!\rightarrow\!\mathrm{spot})"
            r" = 2\,P_{\mathrm{acc}}(\mathrm{spot}\!\rightarrow\!\mathrm{bulk})$"
        ),
        "xy_fraction": (0.50, 0.08),
        "fontsize": 15,
    },
)

CUSTOM_RECT_REGIONS = []
