"""Custom P6 diagram preset saved from the WeldCraft GUI."""



PRESET_NAME = 'Option 3 Concentration'

ANNOTATION_BOX_ALPHA = 0.88

ANNOTATION_BOX_EDGE_COLOR = '#707070'

ANNOTATION_BOX_ENABLED = False

ANNOTATION_BOX_FACE_COLOR = '#FFFFFF'

ANNOTATION_COLOR = '#202020'

ANNOTATION_FONT_SIZE = 16

ANNOTATION_STROKE_COLOR = '#000000'

ANNOTATION_STROKE_WIDTH = 2.5

AREA_SUMMARY_BACKGROUND_COLOR = '#FAFAFA'

AREA_SUMMARY_CLUSTER_ATTRACTION = 0.75

AREA_SUMMARY_CLUSTER_COUNT = 16

AREA_SUMMARY_CLUSTER_SCOPE = 'combined_a_b'

AREA_SUMMARY_CONCENTRATION_BIN_WIDTH = 40

AREA_SUMMARY_CONCENTRATION_MODE = 'linear_x'

AREA_SUMMARY_DENSITY_MODE = 'available_sites'

AREA_SUMMARY_DOT_ALPHA = 0.96

AREA_SUMMARY_DOT_EDGE_COLOR = '#FFFFFF'

AREA_SUMMARY_DOT_EDGE_WIDTH = 0.25

AREA_SUMMARY_DOT_LEGEND_ANCHOR = (0.02, 0.02)

AREA_SUMMARY_DOT_LEGEND_FONT_SIZE = 16

AREA_SUMMARY_DOT_LEGEND_LOCATION = 'lower left'

AREA_SUMMARY_DOT_LEGEND_SIZE_SCALE = 9.0

AREA_SUMMARY_DOT_SIZE = 18.0

AREA_SUMMARY_HALF_DIVIDER_COLOR = '#A0A0A0'

AREA_SUMMARY_LINEAR_CONCENTRATION = (100.0, 0.0)

AREA_SUMMARY_MIN_DOTS_PER_AREA = 30

AREA_SUMMARY_MIN_DOT_SPACING = 7.0

AREA_SUMMARY_OCCUPIED_LABEL = 'Occupied Sites'

AREA_SUMMARY_POSITION_INSET = 5

AREA_SUMMARY_POSITION_JITTER = 0.42

AREA_SUMMARY_POSITION_MODE = 'even_hex'

AREA_SUMMARY_PROFILE_OVERLAY_ALPHA = 0.96

AREA_SUMMARY_PROFILE_OVERLAY_AXIS_COLOR = '#253494'

AREA_SUMMARY_PROFILE_OVERLAY_COLOR = '#253494'

AREA_SUMMARY_PROFILE_OVERLAY_LABEL = 'Measured Concentration Profile'

AREA_SUMMARY_PROFILE_OVERLAY_SHOW_RIGHT_AXIS = True

AREA_SUMMARY_PROFILE_OVERLAY_STYLE = '-'

AREA_SUMMARY_PROFILE_OVERLAY_WIDTH = 2.6

AREA_SUMMARY_PROFILE_OVERLAY_LEGEND_ANCHOR = (0.769, 0.98)

AREA_SUMMARY_PROFILE_OVERLAY_LEGEND_FONT_SIZE = 16

AREA_SUMMARY_PROFILE_OVERLAY_LEGEND_LOCATION = 'upper center'

AREA_SUMMARY_RANDOM_SEED = 104724

AREA_SUMMARY_SHAKE_ATTEMPTS = 8

AREA_SUMMARY_SHAKE_MODE = 'clustered'

AREA_SUMMARY_SHAKE_OUTPUT_MODES = None

AREA_SUMMARY_SHAKE_PASSES = None

AREA_SUMMARY_SHAKE_STRENGTH = None

AREA_SUMMARY_SHOW_AREA_LABELS = False

AREA_SUMMARY_SHOW_DOT_LEGEND = True

AREA_SUMMARY_SHOW_EXPLANATION = False

AREA_SUMMARY_SHOW_HALF_DIVIDER = False

AREA_SUMMARY_SHOW_SOURCE_SINK_BANDS = False

AREA_SUMMARY_SHOW_SOURCE_SINK_LABELS = False

AREA_SUMMARY_SOURCE_SINK_BAND_WIDTH_SCALE = 3.0

AREA_SUMMARY_SOURCE_SINK_EDGE_COLOR = '#303030'

AREA_SUMMARY_SOURCE_SINK_EDGE_WIDTH = 0.8

AREA_SUMMARY_TIME_AVERAGE = True

AREA_SUMMARY_TIME_AVERAGE_SKIP_FIRST_FRAME = True

AREA_SUMMARY_TIME_AVERAGE_USE_CONTINUED = True

AREA_SUMMARY_TOTAL_DOTS = 6500

AREA_SUMMARY_VACANT_LABEL = 'Available Lattice Sites'

AREA_SUMMARY_X_PROFILE_SIGMA = 20.0

AXIS_LABEL_FONT_SIZE = 16

BULK_ANNOTATION_LABEL = 'Bulk Average'

BULK_ANNOTATION_POSITION = (0.25, 0.9)

COLOR_AVAILABLE_SPOT = '#2166AC'

COLOR_CONCENTRATION_LINE = '#253494'

COLOR_EMPTY = '#F2F2F2'

COLOR_HYDROGEN = '#B2182B'

CUSTOM_RECT_REGIONS = []

CUSTOM_TEXT_ANNOTATIONS = ()

DOT_ALPHA_AVAILABLE = 1.0

DOT_ALPHA_HYDROGEN = 1.0

DOT_SIZE_AVAILABLE = 8.0

DOT_SIZE_HYDROGEN = 8.0

FIGURE_SIZE = (13, 6)

GLYPH_BACKGROUND_COLOR = '#F5F5F5'

GLYPH_BIN_SIZE = 32

GLYPH_CAPACITY_GAMMA = 0.3

GLYPH_EDGE_COLOR = '#202020'

GLYPH_EDGE_WIDTH = 0.45

GLYPH_GRID_COLOR = '#D8D8D8'

GLYPH_MAX_RADIUS_FRACTION = 0.9

GLYPH_MIN_RADIUS_FRACTION = 0.38

GLYPH_SHOW_EXPLANATION = True

GLYPH_SHOW_GRID = True

GLYPH_SHOW_SPECIAL_REGION_VALUES = True

HEATMAP_BASELINE_SNAPSHOT_INDEX = 0

HEATMAP_COLORBAR_LABEL = None

HEATMAP_COLORBAR_ORIENTATION = 'vertical'

HEATMAP_COLORMAP = 'RdBu_r'

HEATMAP_CONTOUR_ALPHA = 0.35

HEATMAP_CONTOUR_COLOR = '#303030'

HEATMAP_CONTOUR_LEVELS = (-15, -10, -5, 5, 10, 15)

HEATMAP_DEVIATION_RANGE = (-20.0, 20.0)

HEATMAP_HORIZONTAL_COLORBAR_TICK_COUNT = 5

HEATMAP_MODE = 'deviation'

HEATMAP_OCCUPANCY_RANGE = (0.0, 100.0)

HEATMAP_REFERENCE_MODE = 'regional_bulk'

HEATMAP_RESPECT_AREA_BOUNDARIES = True

HEATMAP_SEPARATE_BASE_AREAS = False

HEATMAP_SHOW_COLORBAR = True

HEATMAP_SHOW_CONTOURS = True

HEATMAP_SIGMA = 18.0

MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = False

NET_FLUX_BAND_COLOR = '#B39DDB'

NET_FLUX_COLOR = '#4A148C'

PANEL_TITLE_FONT_SIZE = 16

PROFILE_AREA_1_LABEL = 'Area 1'

PROFILE_AREA_2_LABEL = 'Area 2'

PROFILE_AXIS = 'x'

PROFILE_BIN_SIZE = 10

PROFILE_GAUSSIAN_SIGMA = 1.5

PROFILE_HALF_TRANSITION_COLOR = '#808080'

PROFILE_SMOOTHING_WINDOW = 1

PROFILE_SPOT_SHADE_ALPHA = 0.22

PROFILE_SPOT_SHADE_COLOR = '#B0B0B0'

PROFILE_SPOT_SHADE_LABEL = 'Special region'

PROFILE_SPOT_SHADE_LABEL_COLOR = '#606060'

PROFILE_X_RANGE = None

PROFILE_Y_RANGE = None

RENDER_MODE = 'area_summary_dots'

SHOW_AREA_SUMMARY_PROFILE_OVERLAY = True

SHOW_BULK_ANNOTATION = False

SHOW_BULK_SOLUBILITY_IN_ANNOTATION = False

SHOW_CONCENTRATION_PROFILE_PANEL = False

SHOW_CONCENTRATION_PROFILE_TITLE = True

SHOW_FRAME_SUPTITLE = False

SHOW_HEATMAP_PANEL = False

SHOW_LEFT_RIGHT_ANNOTATIONS = False

SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False

SHOW_LEGEND = True

SHOW_MAIN_PANEL = True

SHOW_NET_FLUX_PANEL = False

SHOW_PROFILE_HALF_TRANSITION = True

SHOW_PROFILE_SPOT_SHADE = True

SHOW_REGION_ANNOTATIONS = False

SHOW_SITE_STATE_LEGEND = False

SHOW_SOURCE_SINK_ANNOTATIONS = False

SHOW_SPECIAL_REGION_OUTLINES = True

SHOW_SPOT_ANNOTATION = False

SHOW_SPOT_REGION_FILL = True

SHOW_SPOT_SOLUBILITY_IN_ANNOTATION = False

SHOW_TRANSPORT_PROFILE_PANEL = False

SHOW_TRAP_LAYER_ANNOTATION = False

SITE_STATE_AVAILABLE_LABEL = 'Available Lattice Sites'

SITE_STATE_LEGEND_ANCHOR = (0.98, 0.98)

SITE_STATE_LEGEND_FONT_SIZE = 16

SITE_STATE_LEGEND_LOCATION = 'upper right'

SITE_STATE_LEGEND_MARKER_AREA = 128

SITE_STATE_OCCUPIED_LABEL = 'Occupied Sites'

SITE_STATE_UNAVAILABLE_LABEL = 'Unavailable Locations'

SPECIAL_REGION_OUTLINE_COLOR = '#202020'

SPECIAL_REGION_OUTLINE_STYLE = '--'

SPECIAL_REGION_OUTLINE_WIDTH = 1.4

SPOT_ANNOTATION_LABEL = 'Spot Concentration'

SPOT_ANNOTATION_VERTICAL_OFFSET_SCALE = 0.9

SPOT_REGION_FILL_ALPHA = 1.0

SPOT_REGION_FILL_COLOR = '#D9D9D9'

SPOT_REGION_OUTLINE_COLOR = '#202020'

SPOT_REGION_OUTLINE_STYLE = '-'

SPOT_REGION_OUTLINE_WIDTH = 0.8

TICK_LABEL_FONT_SIZE = 16

TITLE = ''

TRANSPORT_PROFILE_COLOR = '#4A148C'

TRANSPORT_PROFILE_INSET_ALPHA = 0.96

TRANSPORT_PROFILE_INSET_FACE_COLOR = '#FBFBFB'

TRANSPORT_PROFILE_MARKER_COLOR = '#1B5E20'

X_LABEL = 'Length'

Y_LABEL = 'Height'
