"""Printer-friendly abstraction: binned, non-overlapping occupancy/capacity glyphs."""

PRESET_NAME = "Printer-Friendly Occupancy Glyphs"

RENDER_MODE = "printer_glyphs"
FIGURE_SIZE = (13, 6)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = True
TITLE = "Hydrogen Distribution (Spatially Binned)"
X_LABEL = "Width"
Y_LABEL = "Height"

COLOR_EMPTY = "#F5F5F5"
COLOR_AVAILABLE_SPOT = "#2166AC"
COLOR_HYDROGEN = "#B2182B"
COLOR_CONCENTRATION_LINE = "#253494"
DIFFUSION_SPEED_COLORS = [
    "#B2182B",
    "#EF8A62",
    "#2166AC",
    "#762A83",
    "#1B7837",
    "#008B8B",
    "#202020",
]

DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 1.0
DOT_ALPHA_HYDROGEN = 1.0

SHOW_MAIN_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = True
SHOW_DIFFUSION_SPEED_PANEL = False

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 5
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = True
PROFILE_HALF_TRANSITION_COLOR = "#707070"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = True
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Spot Region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = False
SHOW_LEFT_RIGHT_ANNOTATIONS = False
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = True
SHOW_TRAP_LAYER_ANNOTATION = True
ANNOTATION_FONT_SIZE = 10
ANNOTATION_COLOR = "#202020"
ANNOTATION_STROKE_COLOR = "#FFFFFF"
ANNOTATION_STROKE_WIDTH = 3.5
ANNOTATION_BOX_ENABLED = True
ANNOTATION_BOX_FACE_COLOR = "#FFFFFF"
ANNOTATION_BOX_EDGE_COLOR = "#707070"
ANNOTATION_BOX_ALPHA = 0.92

CUSTOM_RECT_REGIONS = []

GLYPH_BIN_SIZE = 32
GLYPH_MIN_RADIUS_FRACTION = 0.38
GLYPH_MAX_RADIUS_FRACTION = 0.90
GLYPH_CAPACITY_GAMMA = 0.30
GLYPH_EDGE_COLOR = "#202020"
GLYPH_EDGE_WIDTH = 0.45
GLYPH_BACKGROUND_COLOR = "#F5F5F5"
GLYPH_SHOW_GRID = True
GLYPH_GRID_COLOR = "#D8D8D8"
GLYPH_SHOW_EXPLANATION = True
GLYPH_SHOW_SPECIAL_REGION_VALUES = True

SHOW_SPECIAL_REGION_OUTLINES = True
SPECIAL_REGION_OUTLINE_COLOR = "#202020"
SPECIAL_REGION_OUTLINE_WIDTH = 1.4
SPECIAL_REGION_OUTLINE_STYLE = "--"
SHOW_FRAME_SUPTITLE = False
