"""Transport-rate profile with a compact temporal flux history."""

PRESET_NAME = "Transport Profile and Flux History"

RENDER_MODE = "pixels"
FIGURE_SIZE = (16, 6)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = True
TITLE = "Diffusion as a Result of Random Motion"
X_LABEL = "Length"
Y_LABEL = "Height"

COLOR_EMPTY = "#440154"
COLOR_AVAILABLE_SPOT = "#0000FF"
COLOR_HYDROGEN = "#FF0000"
COLOR_CONCENTRATION_LINE = "#253494"
DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 0.8
DOT_ALPHA_HYDROGEN = 0.95

SHOW_MAIN_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = True
# The transport panel loads the same analysis without adding the older,
# domain-wide flux panel as a fourth column.
SHOW_NET_FLUX_PANEL = False
SHOW_TRANSPORT_PROFILE_PANEL = True

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 10
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = True
PROFILE_HALF_TRANSITION_COLOR = "#808080"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = True
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Special region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = True
SHOW_LEFT_RIGHT_ANNOTATIONS = True
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = True
SHOW_TRAP_LAYER_ANNOTATION = True
ANNOTATION_FONT_SIZE = 11
ANNOTATION_COLOR = "#FFFFFF"

CUSTOM_RECT_REGIONS = []

SHOW_LEGEND = True
SHOW_FRAME_SUPTITLE = True
PANEL_TITLE_FONT_SIZE = 15
AXIS_LABEL_FONT_SIZE = 11
TICK_LABEL_FONT_SIZE = 10
SHOW_CONCENTRATION_PROFILE_TITLE = True

NET_FLUX_COLOR = "#4A148C"
NET_FLUX_BAND_COLOR = "#B39DDB"
TRANSPORT_PROFILE_COLOR = "#4A148C"
TRANSPORT_PROFILE_MARKER_COLOR = "#1B5E20"
TRANSPORT_PROFILE_INSET_FACE_COLOR = "#FBFBFB"
TRANSPORT_PROFILE_INSET_ALPHA = 0.96
