"""Locked preset: two regions with solubility annotations."""

PRESET_NAME = "2 Regions w. Solubility"

RENDER_MODE = "pixels"
FIGURE_SIZE = (12, 6)
MATCH_SIDE_PANEL_HEIGHT_TO_MAIN = True
TITLE = "Diffusion as a Result of Random Motion"
X_LABEL = "Width"
Y_LABEL = "Height"

COLOR_EMPTY = "#440154"
COLOR_AVAILABLE_SPOT = "#0000FF"
COLOR_HYDROGEN = "#FF0000"
COLOR_CONCENTRATION_LINE = "#0000FF"
DIFFUSION_SPEED_COLORS = [
    "#FF0000",
    "#FFA500",
    "#008000",
    "#800080",
    "#A52A2A",
    "#00FFFF",
    "#000000",
]

DOT_SIZE_AVAILABLE = 8
DOT_SIZE_HYDROGEN = 8
DOT_ALPHA_AVAILABLE = 0.8
DOT_ALPHA_HYDROGEN = 0.95

SHOW_MAIN_PANEL = True
SHOW_CONCENTRATION_PROFILE_PANEL = True
SHOW_DIFFUSION_SPEED_PANEL = False

PROFILE_AXIS = "x"
PROFILE_X_RANGE = None
PROFILE_Y_RANGE = None
PROFILE_BIN_SIZE = 5
PROFILE_SMOOTHING_WINDOW = 1
PROFILE_GAUSSIAN_SIGMA = 1.5

SHOW_PROFILE_HALF_TRANSITION = True
PROFILE_HALF_TRANSITION_COLOR = "#808080"
PROFILE_AREA_1_LABEL = "Area 1"
PROFILE_AREA_2_LABEL = "Area 2"

SHOW_PROFILE_SPOT_SHADE = True
PROFILE_SPOT_SHADE_COLOR = "#B0B0B0"
PROFILE_SPOT_SHADE_ALPHA = 0.25
PROFILE_SPOT_SHADE_LABEL = "Spot Region"
PROFILE_SPOT_SHADE_LABEL_COLOR = "#606060"

SHOW_REGION_ANNOTATIONS = True
SHOW_LEFT_RIGHT_ANNOTATIONS = True
SHOW_LEFT_RIGHT_WITHOUT_SINK_SOURCE_ANNOTATIONS = False
SHOW_SOURCE_SINK_ANNOTATIONS = False
SHOW_SPOT_ANNOTATION = True
ANNOTATION_FONT_SIZE = 11
ANNOTATION_COLOR = "#FFFFFF"

CUSTOM_RECT_REGIONS = []
